=== fcommand/azure-devtestlab/schemas/2015-01-01/dtlArtifacts.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "id": "http://schema.management.azure.com/schemas/2015-01-01/dtlArtifacts.json",
    "type": "object",
    "required": [ "title", "description", "targetOsType", "runAzureVMExtension" ],
    "properties": {
        "title": {
            "type": "string",
            "description": "The title of your artifact."
        },
        "description": {
            "type": "string",
            "description": "The description of your artifact."
        },
        "iconUri": {
            "type": "string"
        },
        "tags": {
            "type": "array",
            "items": [
                {
                    "type": "string"
                }
            ]
        },
        "targetOsType": {
            "type": "string",
            "enum": [ "Windows", "Linux" ]
        },
        "runAzureVMExtension": {
            "type": "object",
            "properties": {               
            }
        },
        "parameters": {
            "type": "object",
            "description": "Input parameter definitions",
            "additionalProperties": {
                "$ref": "#/definitions/parameter"
            }
        }
    },

    "definitions": {
        "parameter": {
            "type": "object",
            "required": [ "type" ],
            "properties": {
                "type": {
                    "$ref": "#/definitions/parameterTypes",
                    "description": "Type of input parameter"
                },
                "defaultValue": {
                    "$ref": "#/definitions/parameterValueTypes",
                    "description": "Default value to be used if one is not provided"
                },
                "allowedValues": {
                    "type": "array",
                    "description": "Value can only be one of these values"
                },
                "minLength": {
                    "type": "integer",
                    "description": "Minimum number of characters that must be used"
                },
                "maxLength": {
                    "type": "integer",
                    "description": "Maximum number of characters that can be used"
                },
                "optional": {
                    "type": "boolean",
                    "description": "If this parameter is optional, by default false"
                },
                "description": {
                    "type": "string",
                    "description": "The description of the parameter"
                },
                "displayName": {
                    "type": "string",
                    "description": "The display name of the parameter"
                }
            },
            "description": "Input parameter definitions"
        },
        "parameterTypes": {
            "enum": [
                "string",
                "securestring",
                "int",
                "bool",
                "object",
                "array"
            ]
        },
        "parameterValueTypes": {
            "type": [
                "string",
                "boolean",
                "integer",
                "number",
                "object",
                "array",
                "null"
            ]
        }
    }
}

=== fcommand/azure-devtestlab/Artifacts/artifactExampleRunPowershell/Artifactfile.json
{
    "$schema": "https://raw.githubusercontent.com/Azure/azure-devtestlab/master/schemas/2015-01-01/dtlArtifacts.json",
    "title": "Run PowerShell",
    "description": "Use this to run a script using PowerShell",
    "tags": [
        "Powershell"
    ],
    "iconUri": "",
    "targetOsType": "Windows",
    "parameters": {
        "scriptFileUris": {
            "type": "array",
            "displayName": "File URI",
            "description": "file(s) to download to VM for execution"
        },
        "scriptToRun": {
            "type": "string",
            "displayName": "Script to Run",
            "description": "script file to run"
        },
        "scriptArguments": {
            "type": "string",
            "displayName": "Script Arguments",
            "description": "script arguments to pass",
            "optional": true
        }
    },
    "runAzureVMExtension": {
        "publisher": "Microsoft.Compute",
        "type": "CustomScriptExtension",
        "typeHandlerVersion": "1.3",
        "settings": {
            "fileUris": "[parameters('scriptFileUris')]",
            "commandToExecute": "[concat('powershell.exe -File', ' ', parameters('scriptToRun'), ' ', parameters('scriptArguments'))]"
        }
    }
}
